[tool.poetry]
name = "betterproto-demo"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
betterproto = {extras = ["compiler"], version = "^1.2.5"}
grpcio = "^1.33.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
grpcio-tools = "^1.33.2"
pylint = "^2.6.0"
mypy = "^0.790"
pytest = "^6.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
