# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: helloworld.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class HelloRequest(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass
class HelloReply(betterproto.Message):
    message: str = betterproto.string_field(1)


class GreeterStub(betterproto.ServiceStub):
    async def say_hello(self, *, name: str = "") -> HelloReply:
        request = HelloRequest()
        request.name = name

        return await self._unary_unary(
            "/helloworld.Greeter/SayHello",
            request,
            HelloReply,
        )
